M48
; DRILL file {KiCad 9.0.6} date 2025-12-24T19:30:35-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-24T19:30:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.000
%
G90
G05
T1
X130.275Y-70.275
X130.275Y-110.725
X170.225Y-70.275
X170.225Y-110.725
M30
